### ISSUE TITLE
require('client/utils') and require('utils') requires the exact same file, but it loads it twice

### ISSUE THREAD

**Issue by totty90** [jrburke/requirejs#1226]
var u1 = require('client/utils');
    var u2 = require('utils');
    u1 === u2 // false

Should be true.

**Comment by gcfeng** [comment]
I have the same problem, and the version is 2.1.15. I can reproduce the problem when the code like this:

    +src
        |-- index.html
        |-- main.js
        |-- data
              |-- a.js
    +common.js

the code:

     // main.js
     require([
          '../common',

          'data/a'
     ], function() {});

     // data/a.js
     define(function(require) {
          require('../../common');
     });

     // common.js
     define(function() {
          console.log('common');
     });

The common.js will be executed twice, and then print common twice

**Comment by jrburke** [comment]
This will happen if the module IDs start with '../' and it would lead to the normalized module ID being outside the module ID space.

So, if you ask for '../common' and the module (or a plain require([]) call) is already at the root of the module ID space, then requirejs tries the best it can by loading the module, but treating the module ID internally as "../common", which is really not a normalized ID. 

If some other module asks for "common" and a paths config happens to point that ID to the same file, this behavior will occur.

I originally did this to try to be accommodating to people coming from a script src="" world, but it can lead to this confusing result. In a 3.0 I would likely remove this fuzzy support and throw an error on the "../common" module ID reference as it being un-normalizable.

The fix in the meantime is to not use "../common" module IDs at the top of the module ID space (they make sense if the define()'d module is "some/nested/id" and it wants "../helper" which is normalized to "some/helper", so not outside the top of the module ID space).

Instead, use paths config to set up IDs that are outside the root of the module ID space, as @elternero mentioned.

I do not feel comfortable fixing in this in the 2.x timeframe as it breaks behavior that some people likely rely on now (unfortunately). I filed #1268 to track stricter ID normalization for 3.0.

**Comment by gcfeng** [comment]
Thanks @jrburke

**Comment by totty90** [comment]
Thanks. If any one really needs this feature can use webpack. I moved and
I'm very happy
