### ISSUE TITLE
Possibility of a plugin whose results aren't cached

### ISSUE THREAD

**Issue by nikhilk** [jrburke/requirejs#1259]
Is it possible to create a plugin that does some custom logic to load some data, but the results aren't cached, i.e. each time the data is required it the plugin is invoked?

Normally this is the case for a simple web request, but I'd like to be able to require a bunch of data and load it along-side other script dependencies.

**Comment by rjgotten** [comment]
Create a module that returns a function you can invoke and have that function fetch the data...

**Comment by jrburke** [comment]
@rjgotten's suggestion is the one to use. module exports must be fixed, and not dependent on the caller for the module loader to work correctly.

**Comment by nikhilk** [comment]
The point here was to have the name of the dependency be the url to the data ... of course, I could create a generic data loader module, that has a function that takes a url and loads it.

It was to get the succinct syntax to refer to a data dependency via a data loader that itself was implemented as a requirejs plugin.

**Comment by rjgotten** [comment]
@nikhilk 
What you want is still supported. You can create a loader plugin that returns a function as the loaded module value, which will return data from the URL passed to the plugin when called.

E.g. using `jQuery.ajax` for a succinct example:

```javascript
define(["jquery"], function( $ ) {

  return {
    load : function( name, require, load, config ) {
      var url = require.toUrl( name );

      load( function( params ) {
        return $.ajax({
          url   : url,
          data  : params,
          cache : false
        });
      });
    }
  };
});
```

```javascript
define([ "ajax!../module-relative/url/to/data-source" ], function( ajax ) {
   ajax({ id : 2 }).then( function( data ) { /* ... */ });
})
