### ISSUE TITLE
Reading a gzipped data-main file?

### ISSUE THREAD

**Issue by andrewboni** [jrburke/requirejs#1264]
Not quite sure what the best way to go about this is- maybe someone can shed some light.

After running my dependencies through the `r.js` optimizer, I want to gzip the single resulting concatenated, minified requirejs `data-main=".."` config file, in order to shave ~2mb worth of js libs down to a few hundred kb.

The resulting gzipped file is `main.min.js.gz`. Plugging that in to `data-main=".."` we get:
```html
<script data-main="/scripts/main.min.js.gz" src="//cdnjs.cloudflare.com/ajax/libs/require.js/2.1.15/require.min.js"></script>
```

But, requirejs adds an additional `.js` extension, so the file ends up 404ing (`main.min.js.gz.js`). I realize I can rename the gzipped file to something like `main.min.js`, but will requirejs even be able to parse the gzip encoding? Is that even the right approach, or is there a better way? Any insight is appreciated!

**Comment by neonstalwart** [comment]
gzipping is handled by your browser and server - e.g. https://github.com/h5bp/server-configs-nginx/blob/3db5d61f81d7229d12b89e0355629249a49ee4ac/nginx.conf#L70

to help your server, you can sometimes gzip your files and instruct the server to find the already gzipped file rather than having the server do the work - e.g. https://github.com/h5bp/server-configs-nginx/blob/3db5d61f81d7229d12b89e0355629249a49ee4ac/nginx.conf#L112-L116

**Comment by andrewboni** [comment]
Thanks for the clarification @neonstalwart. I've resolved my issue now- I was trying to do the latter - gzip my own files during my build process and then deploy to s3. The issue was that the `Content-Encoding: gzip` header wasn't being set properly, so my files were just interpreted as gibberish. Fixing the header solved the problem.

**Comment by xander-mbaka** [comment]
@andrewboni how did you fix the header, Im having the same problem. Would you mind showing?

**Comment by andrewboni** [comment]
@xander-mbaka we are serving our files from S3, so I just had to ensure that the `Content-Encoding` header for the js file was set properly. There are many ways to do this (for S3, you can specify the header upon upload. you can also do it manually within the S3 interface), and it depends on how you're serving up your files. If you're using something like Rails or Django to serve up the file, you'll want to read up on how to customize file headers with those frameworks
