### ISSUE TITLE
include/chaining in require.config

### ISSUE THREAD

**Issue by chrylis** [jrburke/requirejs#1269]
I am using RequireJS with Mimosa, which inspects a common config file (`common.js`) to resolve module dependencies for error checking and figuring out when to inline modules for a production build. I'm also using Karma, which needs some other `require.config` setup to configure paths and events for the captive test server.

I am using `paths` to point vendor dependencies to their managed location, but I don't want to keep multiple copies of the path definitions in sync. I'd like a directive in `require.config` that would load an included `require.config`, process its directives, and then overlay the current config's overrides:

    require.config({
        include: '/base/common.js',
        paths: { test: '/base/test' },
        callback: window.__karma__.start
    });

where `common.js` is:

    require.config({
        paths: {'when': 'vendor/when/when'}
    });

**Comment by jrburke** [comment]
This sounds like the (deps config](http://requirejs.org/docs/api.html#config-deps). Note that module IDs, not paths, should be passed as deps array values, and it does not block other require() calls happening. However, if you have other top level calls and you want them to execute after all the config is loaded, place them in the `callback` config option (described just below the `deps` config option in that link).
