### ISSUE TITLE
How I can use manifest for modular loading?

### ISSUE THREAD

**Issue by tamtakoe** [jrburke/requirejs#1274]
I create modular build with scripts bundles. There are several amd modules in builded module file. 
<pre>
manifest.json or object in memory
"source/somePath/amdScriptName1": "build/module1",
"source/somePath/amdScriptName2": "build/module1",
"source/somePath/amdScriptName3": "build/module2",
"source/somePath/amdScriptName4": "build/module1",
"source/somePath/amdScriptName5": "build/module3",
"source/somePath/amdScriptName6": "build/module3",
...
</pre>
How to load the module with the necessary script, guided by the manifesto, instead of downloading the script separately?

**Comment by jrburke** [comment]
If you write out a [bundles config](http://requirejs.org/docs/api.html#config-bundles) for the loader that lists the module IDs that are in each bundle ID, that is the suggested way to do that.

**Comment by tamtakoe** [comment]
bundles: {
    "build/module1": ["amdModule1", "amdModule2", "amdModule4"],
    "build/module2": ["amdModule3"],
    "build/module3": ["amdModule5", "amdModule6"],
}

path: {
    "amdModule1": "build/module1",
    "amdModule1": "build/module1",
}

**Comment by tamtakoe** [comment]
Do I understand that these configs are equivalent?
```javascript
require.config({
    bundles: {
        "build/module1": ["amdModule1", "amdModule2", "amdModule4"],
        "build/module2": ["amdModule3"],
        "build/module3": ["amdModule5", "amdModule6"],
    }
})
```
```javascript
require.config({
    path: {
        "amdModule1": "build/module1",
        "amdModule2": "build/module1",
        "amdModule3": "build/module2",
        "amdModule4": "build/module1",
        "amdModule5": "build/module3",
        "amdModule6": "build/module3",
    }
})
```
