### ISSUE TITLE
require-js over web-sockets or from string ? 

### ISSUE THREAD

**Issue by mc007** [jrburke/requirejs#1277]
I posted this already on stack-overflow(http://stackoverflow.com/questions/28341201/load-require-js-modules-over-web-sockets), but here as issue: 

Is there already an official way to create require-js/AMD modules from a string (delivered by a web-socket)?

I am working on a real-time editor for Dojo/AMD apps which is currently using require.undef and then re-requires the module url (bad with cache). This is working ok and updates module instances with a delay of 2-3 seconds (still slow). That allows you to apply code changes to your application directly from your IDE. My Node.js file watcher is instant (5ms delay) and now I'd like to reload the module from a web-socket message which contains all the code.

When looking at the Dojo code, its loading modules via regular doc.createElement("script"). Now I am wondering I need to patch just the loader or there is a more direct way to archive this.

Possibly there is already a way to make require-js working completely over web-sockets.

Any ideas are welcome.

thank you!

**Comment by jrburke** [comment]
If you are using Dojo's AMD loader, then the advice may be different, better to ask in that community. In general, I will say that hot code reloading will be difficult to scale well. 

While something like .undef allows to undefine a module, some other smarts need to know how to traverse the entirety of the the app's dependency tree to see what other modules then also need to be unloaded if a base dependency changes and is undef()'d. That, coupled with global side effects of modules (like creating widgets in a page, so the DOM elements are in the global space), make hot code reloading susceptible to bugs that would not normally be seen if the page was just reloaded as a whole.

So in general, I suggest just going with a trigger that knows how to `location.reload(true)` on module changes will result in fewer edge case issues.

On the technical use of using web sockets to push updates: perhaps use the connection to push down the .undef() calls, then send the define()'d wrapped modules with their IDs, then end it with a require([]) calls to bring those modules into being. That way, no overloading of the module loader needs to be done. This is assuming the web sockets connection is there primarily to push updates.

But I would be really wary about trying to do hot code reloading. There will be issues that are only solved by reloading the whole page.

Closing as a discussion ticket.

**Comment by mc007** [comment]
Great! Thank you, I will try that, and yes, I am aware about the dependency problems (which is none in my case since I made my API up to that).

Anyway, the major problem with require-js/one-module-per-file is: in large applications (1000+ modules) you don't want reload the page and re-do the steps to see finally your code changes (in FF = 20+ sec), with hot reloading: 1-2 secs. 

But please let me ask this: is there chance to make require-js accepting strings instead of added 'script' nodes with a onload callback? And if so, do you have some hints where in require-js its the best place to start? 

I really wanna see that happening, the speed is just great after toying a little. I don't mind the efforts then.

thank you again,
guenter

**Comment by jrburke** [comment]
If using requirejs, then you can override [requirejs.load()](https://github.com/jrburke/requirejs/blob/master/require.js#L1833) to do different things, and call `context.completeLoad(moduleName);` when loading is considered complete for a module. The importScripts/worker branch of requirejs.load shows this best, since importScripts is synchronous, so easier to follow.

**Comment by mc007** [comment]
:+1: that's just great, thank you for your help. if i got anything working, i will let you know.

**Comment by themolecule** [comment]
Hey guenter, were you ever able to get this working?

I have a similar case, which is not about hot code reloading, but more that I have certain js libraries stored in c++ websocket server classes.

A mechanism to load them over http is complicated because they don't exist as static files, and a websocket mechanism would be simpler for creating my API.
