### ISSUE TITLE
require.specified() not working

### ISSUE THREAD

**Issue by reflectiveSingleton** [jrburke/requirejs#1305]
This should work but requirejs currently doesn't seem to specify modules correctly.

```javascript
// no module specified by that name...so far so good.
expect( require.specified('test') ).to.be(false); // PASS

// define/specify a module...
define('test', [], function() {});

// check to see if that module is specified
expect( require.specified('test') ).to.be(true); // FAIL
```

It **does** work once you require() the module...but specified() is supposed to work without that:

```javascript
// no module specified by that name...so far so good.
expect( require.specified('test') ).to.be(false); // PASS

// define/specify a module...
define('test', [], function() {});

// this should fail, yet it does not
expect( require.specified('test') ).to.be(false); // PASS

// require() the module...
require(['test']);

// now this works...
expect( require.specified('test') ).to.be(true); // PASS
```

I am working on a project which needs to know if a module has been specified (and not yet resolved). From all my googling it seems like this should work...

**Comment by Cameri** [comment]
requirejs.specified IS working.

Got this from the docs:
> parentRequire.specified(moduleName): Returns true if the module has already been requested or is in > the process of loading and should be available at some point.

Perhaps, what you want is requirejs.defined().

**Comment by reflectiveSingleton** [comment]
I actually was using defined(), from what I understand the difference between .defined() and .specified() is that defined modules are ones which have been resolved already. Using .specified() was (from what my google-fu told me) the correct way to detect if a module had been registered but not yet resolved.

Ref: http://stackoverflow.com/a/15029028

**Comment by reflectiveSingleton** [comment]
I just verified again (to make sure I wasn't going insane)...and neither .defined() nor .specified() works.

```javascript
// no module specified by that name...so far so good.
expect( require.specified('test') ).to.be(false); // PASS

// define/specify a module...
define('test', [], function() {});

// check to see if that module is specified or defined
expect( require.specified('test') ).to.be(true); // FAIL
expect( require.defined('test') ).to.be(true); // FAIL
```

**Comment by jrburke** [comment]
Ah, so this does not work because of the [multiple context support](http://requirejs.org/docs/api.html#multiversion). Until a top level require call claims the define registrations, it is unclear what context, even the default one, owns it.

Doing any require() call should claim them though. I would expect this test might work:

```javascript
// no module specified by that name...so far so good.
expect( require.specified('test') ).to.be(false); // PASS
expect( require.defined('test') ).to.be(false); // PASS

// define/specify a module...
define('test', [], function() {});

require([]);

// check to see if that module is specified or defined
expect( require.specified('test') ).to.be(true); // FAIL
expect( require.defined('test') ).to.be(true); // FAIL
```

**Comment by reflectiveSingleton** [comment]
Thanks @jrburke ...that did the trick!

FWIW, I would suggest some sort of note to be added to the `.specified()` API documentation concerning this. It isn't apparent from glancing at the docs that this might be an issue.
