### ISSUE TITLE
add virtual modules

### ISSUE THREAD

**Issue by tamtakoe** [jrburke/requirejs#1310]
I wrap JSZip module to virtual JSZipGlobal module (which set variable to window), but I see extra request for JSZipGlobal.js

```js
paths: {
    JSZip: 'vendor/js-xlsx/dist/jszip',
    XLSX: 'vendor/js-xlsx/dist/xlsx'
},   
shim: {
    JSZipGlobal: {
        init: function(JSZip) {
            window.JSZip = JSZip;
        },
        deps: ['JSZip']
    },
    XLSX: ['JSZipGlobal'],
}
```

May not make a request, if I write `null` instead of the path?
```js
paths: {
    JSZip: 'vendor/js-xlsx/dist/jszip',
    XLSX: 'vendor/js-xlsx/dist/xlsx',
    JSZipGlobal: null
}
```

**Comment by tbranyen** [comment]
Your shim configuration is incorrectly set up, try:

``` javsacript
shim: {
  JSZip: { exports: 'JSZip' },
  XLSX: ['JSZip']
}
```

**Comment by jrburke** [comment]
Going to close for now, but feel free to continue discussion. We can reopen it as needed.

**Comment by tamtakoe** [comment]
@tbranyen it is not work, because `JSZip` check that site use requirejs and use code as amd-module which return `JSZip` but not set `window.JSZip` (`{export: 'JSZip'}` doesn't work).

`XLSX` is not amd-module, it use variable `JSZip`.

Unfortunately if I use`shim: {XLSX: ['JSZip']}` I cant't set argument to `define`. That is why I wrap `XLSX.js` in `define` by my site builder.

```js
//XLSX-amd.js
define(["JSZip"], function(JSZip) {<%= contents %> window.XLSX = XLSX; return XLSX;});
```
