### ISSUE TITLE
Issue with Amplitude Analytics

### ISSUE THREAD

**Issue by pcothenet** [jrburke/requirejs#1311]
Hi!

I was having some issue with a mismatch error:
```
Uncaught Error: Mismatched anonymous define() module: function (){return require("1")}
```
(which would happen approx. one out of every 10 page load)

By trial and error, I think I've cornered the issue to the javascript from amplitude analytics (http://d24n15hnbwhuhn.cloudfront.net/libs/amplitude-2.0.3-min.js), which starts with:

```javascript
if("function"==typeof define&&define.amd){define(function(){return require("1")}
```

I've reported that issue to their report but I'm wondering if there's a recommended way to load tracking javascript with requirejs (I'm loading them all via Segment.io).

Thanks for your help!

**Comment by pcothenet** [comment]
OK, [this](https://github.com/amplitude/Amplitude-Javascript/issues/3) confirms it.

I'm still a bit confused. What's the best way to ensure that require.js is loaded before calling the segment script?

**Comment by jrburke** [comment]
Normally it is best to do all script loading using requirejs APIs once require.js has been loaded in the page. If the script is not compatible with require.js for some reason, then as long as it is placed before require.js tag and the HTML script tags do not use the `async` attribute, it should work out.

Judging by the resolution in the other ticket, it sounds like this was worked out already, so will close this issue too.
