### ISSUE TITLE
Need stub for minified projects

### ISSUE THREAD

**Issue by mcd-php** [jrburke/requirejs#1312]
I have some project, I build it with `r.js`. It still has references to functions `define()`, `require()` etc., and it doesn't work without original `require.js`.

But the project is complete in itself, it needs no more files.

Is where any stub implementation of `require.js` - functions `define()` and `require()` seraching only in some local object, or builder what does not make them alltogether ?

Ideally, it should be wrapped in immediately-invoked function, so if other scripts in page still use full `requirejs`, it will not damage the definitions.

**Comment by a-ignatov-parc** [comment]
You should check [almond.js](https://github.com/jrburke/almond)

**Comment by jrburke** [comment]
In addition to almond, other options are listed here too:
https://github.com/jrburke/requirejs/wiki/AMD-API-Shims
