### ISSUE TITLE
Period in package name causes no path resolution

### ISSUE THREAD

**Issue by cmwelsh** [jrburke/requirejs#1313]
I'm using `react-loader` and this commit from their project doesn't play well with RequireJS:

https://github.com/quickleft/react-loader/commit/f5556e1a60ada508630c88042314761bf4edb1c3

Is it possible the period in the package name is causing the issue? Everything is kosher if I adjust the package name from `spin.js` to `spin-js`, but that means I have to get my hands dirty and fork things.

**Comment by cmwelsh** [comment]
This is a duplicate of #1083

**Comment by jrburke** [comment]
You can use [nodeIdCompat](http://requirejs.org/docs/api.html#config-nodeIdCompat) to fix the react-loader commit issue. That allows those types of '.js' suffixed IDs to work. They are unfortunate, and unnecessary, but are allowed by node, so it complicates the story.
