### ISSUE TITLE
module.parent

### ISSUE THREAD

**Issue by tadjik1** [jrburke/requirejs#1316]
Hello.
Thanks for great tool, it's very useful and well-documented. Right now I'm trying to implement something like logger service for my app and have a trouble with detection parent module.
I want initialize my module this way:

```
// app/router.js
define(function(require, exports, module) {
  'use strict';

  var logger = require('services/log')();

  //and in some place

  myMethod: function () { logger.info('myMethod invoked'); }
});

// sevices/log.js

define(function(require, exports, module) {
    'use strict';

    module.exports = function () {
        var name = module.parent.split('/').slice(-2).join('/');

        return {
            info: function () {
                console.info(name + ':', arguments);
                /**
                 * expect in console:
                 * 'app/router.js': ['myMethod invoked']
                 */
            }
        }
    }
});
```

So my question:
@jrburke  Is it possible to implement module.parent in your commonjs realization?

**Comment by neonstalwart** [comment]
one option you have available right now is to pass `module` to your logger and then use `module.id` rather than `module.parent`.

```js
var logger = require('services/log')(module);
```

**Comment by tadjik1** [comment]
yep, it's true. And one more question, @neonstalwart  how it will works with minified js?

**Comment by neonstalwart** [comment]
there should be no problems when minified. the id should be the same value after building since the module id is not coupled to the filename. it shouldn't take much effort to verify what happens if you want to be sure.

**Comment by tadjik1** [comment]
thank you very much @neonstalwart
