### ISSUE TITLE
nested requirements when define?

### ISSUE THREAD

**Issue by pcompassion** [jrburke/requirejs#1317]
I'd like to `define A`, but A should `require` B and B `require` C (for the sake of r.js)

Any of the these two are correct?
Should I ask this in SO?

```
define([
    'module'
], function(module) {
    require(['C'], function() {
        require(['B'], function() {

            var A;

            return A;
        });
    });
});


require(['C'], function() {
    require(['B'], function() {
        define([
            'module'
        ], function(module) {
            var A;

            return A;
        });
    });
});
```

**Comment by cmwelsh** [comment]
This is a StackOverflow question but here is the answer anyway...

A.js

    define([
        'B'
    ], function (
        B
    ) {
        console.log('a loaded');
        console.log(B);

        function A() {
        }

        return A;
    });

B.js

    define([
        'C'
    ], function (
        C
    ) {
        console.log('b loaded');
        console.log(C);

        function B() {
        }

        return B;
    });

C.js

    define([
    ], function (
    ) {
        console.log('c loaded');

        function C() {
        }

        return C;
    });

Please go ahead and close if this solves your issue.

**Comment by pcompassion** [comment]
Thanks for the answer. But I think you misunderstood my question.

(my wording is a bit confusing)

`C` has all the `B` (C requires B)
`A` depends on `B`

'''
require(C) {  // require C first so that when r.js runs, I can factor out C as a common module
  require(A)
}

define(B) { // A depends on B, actually subset of B
 var A;
 return A;
}

define(B) { // C depends on B
 var C;
 return C;
}
'''
