### ISSUE TITLE
data-main Entry Point documentation issue (I think)

### ISSUE THREAD

**Issue by mmenozzi** [jrburke/requirejs#1328]
Hi,
here (https://github.com/jrburke/requirejs/blob/master/docs/api.html#L180, so here http://requirejs.org/docs/api.html#data-main) you say that we have to require **scripts/config** and then do other require calls. But above you used **scripts/main** as configuration script for requireJS and there is no baseUrl in main.js so the baseUrl should be **scripts**.

So I think that documentation is wrong because requiring **scripts/config** will cause a loading error. The right version should be:

```
<script src="scripts/require.js"></script>
<script>
require(['main'], function() {
    // Configuration loaded now, safe to do other require calls
    // that depend on that config.
    require(['foo'], function(foo) {

    });
});
</script>
```

Am I right?

**Comment by jrburke** [comment]
requirejs takes the data-main value, pulls off the path in that file, sets that as the baseUrl, then does a require([]) for the remaining value. So for data-main="a/b/c/main", "a/b/c" is set to the baseUrl, then a require(["main"]) is done.

The main script can then change the baseUrl to some other value if it wants. It can also do other require() calls at that point. Multiple requirejs.config() calls can be done in an app, and the loader tries to merge the calls to about two levels deep in the config object, with the last requirejs.config() call winning for any conflict in values.

What you posted also works fine. If you want to do multiple require() calls in the HTML then what you posted is required, and the rest of the data-main doc section goes into why that is the case.

Closing as a discussion ticket, feel free to continue discussion here.
