### ISSUE TITLE
Error Callback in define()

### ISSUE THREAD

**Issue by ZaValera** [jrburke/requirejs#1330]
```javascript
define([
    'modules/firstModule',
    'modules/secondModule'
], function (firstModule, secondModule) {
    //Will be returned if all dependencies are successfully loaded
    return {
        firstModule: firstModule,
        secondModule: secondModule
    };
}, function () {
    //Return something else if one of dependencies cannot be loaded
    return {
        firstModule: null,
        secondModule: null
    };
});
```

**Comment by jrburke** [comment]
define() is a way to declare a module and its dependencies independent of any runtime execution. There is an an error handler for `require([], function(){}, function(err) {})` cases, and config like [paths fallbacks](http://requirejs.org/docs/api.html#pathsfallbacks) to deal with loading errors.

Closing as a discussion ticket.

**Comment by ZaValera** [comment]
Why not give the opportunity to handle the error in the module itself. Handle the error at the top of the chain of dependencies is not easy and almost does not make sense.
