### ISSUE TITLE
Using requirejs within a jquery plugin - Question

### ISSUE THREAD

**Issue by settysreekanth** [jrburke/requirejs#1331]
I am new to requirejs. Can I use requirejs within a jquery plugin?

My requirement is to develop new plugin with modularity in the code? I am planning to use requirejs for AMD pattern and call required modules wihin jquery plugin boilerplate.

Pseudo code:

(function($, window, document, undefined){

$.extend(Plugin.prototype, {
init: function(){
 require([module1],function(mod1){
        My logic using module1....
});
}

});

})(jQuery, window, document);
Here module1 is a AMD module.

Is this a good approach ?

**Comment by settysreekanth** [comment]
@jrburke  your suggestion please?

**Comment by jrburke** [comment]
It seems fine as long as you are OK with the init: logic inside the require([]) callback to be done asynchronously.

Closing as a discussion ticket, feel free to continue discussion here though.
