### ISSUE TITLE
requirejs is not a PHP project

### ISSUE THREAD

**Issue by wwb-dev** [jrburke/requirejs#1346]
![2015-05-12 17 28 03](https://cloud.githubusercontent.com/assets/1448791/7583975/a41aed48-f8cc-11e4-854f-f1d43a066ab0.png)

**Comment by SimenB** [comment]
That is just GitHub showing what language is mostly used in the repo.

![image](https://cloud.githubusercontent.com/assets/1404810/7596495/5dbbadb6-f8ee-11e4-8012-448ff7bd6a6b.png)

It doesn't seem to be supported by the actual data though...
https://github.com/jrburke/requirejs/search?l=php
![image](https://cloud.githubusercontent.com/assets/1404810/7596536/a20f402c-f8ee-11e4-9eda-91217ad6cacb.png)

**Comment by jrburke** [comment]
It is not ideal that it classifies as PHP, since there are only 4 php files in the project. I contacted github support to see if there is anything I can do to control that classification. I did not see anything in the options.

**Comment by jrburke** [comment]
After hearing back from GitHub support, the detection library seems to think the large PHP files in tests/browsertests are part of the main project. In order to avoid confusion, and since they are standalone tests anyway, I moved them to the requirejs/browsertests.

**Comment by jrburke** [comment]
Forgot to hyperlink the detection library, in case I hit this problem again:

https://github.com/github/linguist
