### ISSUE TITLE
useStrict: false is ignored in 2.1.17

### ISSUE THREAD

**Issue by samspot** [jrburke/requirejs#1348]
After updating from 2.1.15 -> 2.1.17 we're seeing 'use strict' in our requirejs output.  We are running it from grunt-contrib-requirejs@0.4.4.

I see some issue activity related to 'use strict' but I must confess I'm having trouble following it.

**Comment by jrburke** [comment]
Yes, some should show up, based on the change in jrburke/r.js#689, where it was being too aggressive. Mainly: 'use strict' inside functions should stay around, and this is should really be safe if the modules were tested before optimization, it actually maintains their functionality more correctly.

If there are top level 'use strict' calls not being stripped, then that needs more discussion, probably some code samples.

**Comment by samspot** [comment]
OK, thanks for the clarification.  For us, this is causing an issue in Safari due to their incorrect implementation of strict.  We traced it to the lib Q.js, but only after minification.  Would be nice to still have the option to strip all, but if this is intended we can use some other process in the pipeline to strip the rest of them.

**Comment by jrburke** [comment]
You can use the [onBuildWrite config option](http://www.ericfeminella.com/blog/2012/03/24/preprocessing-modules-with-requirejs-optimizer/) to do more aggressive filtering, something like this might be enough:

```javascript
onBuildWrite: function(id, path, contents) {
  return contents.replace(/['"]use strict['"];/g, '');
}
```

That is the old regexp that was used, so it should give a similar result. Going to close, as a planned change, with a workaround if the old behavior is wanted. However, feel free to continue conversation here if it helps.
