### ISSUE TITLE
Including require.min.js in npm

### ISSUE THREAD

**Issue by hanifbbz** [jrburke/requirejs#1349]
Thanks for the awesome Requirejs library.

We have a enterprise application that uses requirejs. Recently we dumped bower in favour of npm. Therefore we directly copy a handful of front-end javascript libraries to the build directory where they will be accessible as AMD modules. Almost all javascript libraries that we use come with a minified front-end-ready version (angular, angular-animate, etc.). However we have to manually compress requirejs.

I was wondering if it's possible to include a minified version of require.js (`browser/require.min.js`) in the NPM package so that we can directly copy it pretty much like the rest of our front-end packages?

**Comment by jrburke** [comment]
There is a minified version of require.js on the [download site](http://requirejs.org/docs/download.html#requirejs), but no plan to put that into package manager deliverables.

**Comment by michaelsogos** [comment]
HI,

I agree with the request from @userpixel  but with a little edit. Can you update BOWER package to include the minified version and its sourceMap?

Have a nice day
