### ISSUE TITLE
Intermittent JS loading error

### ISSUE THREAD

**Issue by nikolas** [jrburke/requirejs#1351]
About 1/8 of the time I load my requirejs app, it doesn't load, and I get this error in the JS console:
> Uncaught TypeError: define is not a function
![2015-05-18-094220_1037x219_scrot](https://cloud.githubusercontent.com/assets/59292/7682004/92a96bdc-fd42-11e4-9423-3a4c7d57265e.png)

I'm using RequireJS 2.1.17, Chromium version 44.0.2391.0 on Ubuntu 15.04 (64-bit).

Here's how I'm including require.js:
https://github.com/ccnmtl/worth2/blob/master/worth2/templates/base.html#L163

**Comment by jrburke** [comment]
This seems more like a problem with perhaps the CDN/server complex than requirejs? Those 400 errors look suscpicious. It could be something like that or some other part of the template injecting code in the page before requirejs is loaded? Not sure where that app.js is loaded, but if it gets loaded before the require.js tag, maybe if it uses the async or defer tag, or the requirejs tag ends up with one of those attributes, then that could be the problem too.

On the face of it though, it looks like more of an HTML setup/server connection issue than requirejs on its own. So going to close for now, but feel free to continue discussion here and we can reopen if something is identified.

**Comment by carlosdubus** [comment]
I'm also getting this error when I refresh too often while developing.  I get "define is not a function" in my main js file(loaded using the data-main attribute). The only script tag in my page is the requirejs tag: <script src="require.js" data-main="main.js"></script>
If I refresh again the issue is solved. I think it has something to do with browser cache but I have no clue.

**Comment by NomAnor** [comment]
I got the same problem with Firefox. When I turn strict mode on, everything loads find.

**Comment by moloko** [comment]
dunno if it helps but I had a project that got a 400 error when trying to load require.js but ONLY in 64-bit Internet Explorer (and only on the client's server).

It worked absolutely fine in 32-bit IE
