### ISSUE TITLE
Define paths is breaking the dependencies

### ISSUE THREAD

**Issue by lagden** [jrburke/requirejs#1355]
It's my config:

```javascript
requirejs.config({
  baseUrl: '/js/lib',
  ...
```
I have a lib `growl` inside of `/js/lib` folder:

```
├── lagden
│   ├── growl
│   │   ├── growl.js
│   │   └── lib
│   │       └── util.js
```

If I just call like example below:

```javascript
define(['lagden/growl/growl'], function(Growl) {
  //...
```
**Everything works fine!**

---

Now, if a put some path:

```javascript
requirejs.config({
  baseUrl: '/js/lib',
  paths: {
    'growl': './lagden/growl/growl',
    //...
```

and try:

```javascript
define(['growl'], function(Growl) {
  //...
```

**I've got a error** `/js/lib/lib/util.js `

Because inside the `growl.js` I have `define(['./lib/util.js'], function...`

---

There's some way to define it correctly or I have to use like the written in the beginning?

**Comment by rjgotten** [comment]
Use `map` not `paths`:

The `map` settings works at the module ID level and takes into account relative module IDs, resolving them as you would expect. The `paths` setting works at the file URL level, which is one level lower, and will *not* work for your usecase.

**Comment by lagden** [comment]
@rjgotten that's it!!

Very interesting this feature!!

Tks!
