### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by divinzer** [jrburke/requirejs#1356]
I want to use [Sourcegraph](https://sourcegraph.com) for requirejs code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/jrburke/requirejs. (It should only take 30 seconds.)

Thank you!

**Comment by jrburke** [comment]
I am unclear why I need to sign in in github for this: the repo is already public, and I would prefer to not give them a github access token for something that seems like they can derive from the already public data.

Going to close for now, but feel free to continue discussion here.
