### ISSUE TITLE
Uncaught Error: Load timeout for modules: xx.js

### ISSUE THREAD

**Issue by fiture** [jrburke/requirejs#1357]
Here are this situation:

```javascript
<script src="require.js" data-main="xx.js"></script>
<script>
    require(['xx.js'], function(xx){
        //would not execute and throw an error: "Uncaught Error: Load timeout for modules: xx.js"
    })
</script>
```

**Comment by jrburke** [comment]
data-main strips the '.js' part and treats it like a module ID, 'xx'. If a require(['xx.js']) comes in later, it is a different ID, but when the ID is converted to a path to load, the loader already sees it has loaded that path, and does not try to loader it again. However, the module in that file was already claimed by the 'xx' ID, and that sort of error is generated.

It is best to just use module IDs for both cases, this should work out:

```javascript
<script src="require.js" data-main="xx"></script>
<script>
    require(['xx'], function(xx){
        //would not execute and throw an error: "Uncaught Error: Load timeout for modules: xx.js"
    })
</script>
```

Going to close as the suggested workaround. Longer term, I want to disallow using URLs for IDs, which would have avoided this issue, but that is more like a 3.0 change.

**Comment by fiture** [comment]
Thank you for your answers carefully. I've worked it out.
