### ISSUE TITLE
Expire cache on require.js data-main main.js

### ISSUE THREAD

**Issue by conger** [jrburke/requirejs#1363]
I'm using require.js and r.js to package my AMD modules. I'm using jquery & requirejs via the following syntax to avoid the browser cache after deployment.

< script data-main="scripts/main.js?bust=1.9" src="scripts/require.js" >< /script >

but now require.js tries to get main.js from /, not /script, so i get the  404 error.

Since i have package all the js files into main.js, so i can't use this urlArgs to avoid the cache , How should i deal with this issue?

**Comment by jrburke** [comment]
In this case, it is likely best to not use data-main and just use a separate script tag for the load:

```html
<script src="require.js"></script>
<script>require(['scripts/main.js?bust=1.9'])</script>
```

You might need to adjust that to set baseUrl first before doing the require([]), but no plans to support more variations in data-main parsing.
```

**Comment by nitinsurana** [comment]
+1 to add urlArgs to data-main url.
