### ISSUE TITLE
TypeScript definition missing "module" module for module.config()

### ISSUE THREAD

**Issue by httpete** [jrburke/requirejs#1366]
I am using .ts and require, but it barks at me if I do:

/// <amd-dependency name="module" path="module" />

and typescript barks that module has no property config. The typings should have this no?

**Comment by jrburke** [comment]
I am not sure I follow. I do not maintain a typescript definition for requirejs? Where does the definition come from?

**Comment by httpete** [comment]
Oh I got the typing from DefinitelyTyped.  
```javascript
/// <reference path='../../typings/angularjs/angular.d.ts' />
/// <reference path='../../typings/requirejs/require.d.ts' />
/// <reference path='../../typings/tsd.d.ts' />

/// <amd-dependency path="module" name="module"/>

'use strict';

export class DashboardService {

    static $inject = ['$resource'];

    constructor(private $resource) {
            module.config(); //this barks in typescript 1.5!!!!!!
    }

    getDashboardService() {
        return this.$resource('http://localhost\\:3000/realmen/:entryId', {}, {
            query: {method:'GET', params:{entryId:''}, isArray:true},
            post: {method:'POST'},
            update: {method:'PUT', params: {entryId: '@entryId'}},
            remove: {method:'DELETE'}
        });
    }
}
```

**Comment by jrburke** [comment]
Hmm, I am not familiar with that, but taking a quick look maybe it comes from here? https://github.com/borisyankov/DefinitelyTyped/tree/master/requirejs so I suggest creating a ticket over in that repo for the issue. I will close this one out here since this repo cannot do the fix.

**Comment by httpete** [comment]
I have this if anyone else needs, it will make your ts compiler happy. You can add to your tsd.d.ts or a file referenced by it: Thank you James.

```


declare module 'module' {
    var mod: {
        config: () => any;
        id: string;
        uri: string;
    }
    export = mod;
}


```
