### ISSUE TITLE
Fallback baseUrl?

### ISSUE THREAD

**Issue by anishathalye** [jrburke/requirejs#1371]
I'm thinking about how to implement fallbacks for the use case where you have a CDN serving content, but in case that fails, you have another domain that serves the same stuff. For example, you may have `cdn.mysite.com` point to your CDN, but in case that goes down, you have `static.mysite.com`. What's a good way to set up fallbacks for that?

There are path fallbacks, but it seems that it involves a lot of repetition if you have a lot of paths (see [this StackOverflow answer](http://stackoverflow.com/a/12075296)). Is there any better way of doing this?

Would it be useful to add a baseUrl fallback feature?

**Comment by jrburke** [comment]
I believe it is enough to just do a new `requirejs.config({baseUrl: 'new/baseurl'})` config call if you want to change the baseUrl: requirejs.config() calls are merged, up to about two levels deep.

I am pretty sure that works, but if you find it does not, a small test case would be helpful to identify a fix.
