### ISSUE TITLE
Best way to insert `requirejs.config` call in build?

### ISSUE THREAD

**Issue by pags** [jrburke/requirejs#1377]
I need to include a `requirejs.config()` call in my build file in order to utilize `map` with almond.

I've created a module (let's call it the "config module") which makes the config call.

If I add the config module to the top level `deps` array in my config, and pass the config to the r.js optimizer, the module is not included in the build file at all (bug or feature?).

If I additionally add the config module to `include` (passing an Array of things like `{ name : '...', include : ["the config module"] }` to `modules`), it is now included in the build, but toward the end of the file, after it is needed.

My question is, how do I get my config call included in the appropriate place in my build output?  This is all with version 2.1.18.

**Comment by pags** [comment]
`deps` weren't included in build file because of using `exclude` instead of `excludeShallow`.

Unfortunately the modules in `deps` are just defined in-line with everything else and not made proper dependencies of the main module.  What am I missing?

**Comment by jrburke** [comment]
If you are building with almond, you can do the build such that the target of the build is 'almond', then do include for this special config module then the actual main module, something like this:

```javascript
{
  name: 'almond',
  include: ['config', 'main']
  out: 'built.js'
}
```

That way, almond is first (and would be hoisted to the top anyway since it defines an AMD API), then config will be in the file, followed by the actual modules you want included in the build.

I think that is enough so closing, but feel free to add more info if that does not work.

**Comment by pags** [comment]
Unfortunately, an appropriate\unique "name" is needed for plugins down the line (specifically, the require-css plugin), so this setup won't work for me.

**Comment by jrburke** [comment]
I'm not sure I follow what needs to be named in the 'config' part. Maybe fleshing out more of the example would help.

**Comment by pags** [comment]
Last attempt was too hasty, I updated the require-css plugin and that fixed the issue.  The issue now is that I get something like:

`Error: ENOENT, no such file or directory 'almond/almond.js-temp'`

Seems to have something to do with the fact that, internally in the r.js optimizer, there's something called `_buildPath` that is set off of module.name, and doesn't take module.out into account.  Does that sound correct?
