### ISSUE TITLE
cannot install Bracket extension

### ISSUE THREAD

**Issue by jpfux145** [jrburke/requirejs#1381]
hi,

I´m a german guy so please excuse me mistakes for writing.

Now, my problem:

Ich tried to install an extension, for example emmet by braket.
I´m sitting behind a proxy and have edited the "preference file" correctly. I have got a package in the folder extensions\user\brackets-emmet but an error message named:

 "Installation failed. The extension encountered an error while starting up".

 I think, the reason is my userid: sp#7034 but what can I do to change the installation folder ?

In the developer console, I got the following messages:

Error setting menu item shortcut: 1ErrorNotification.js:125 window.console.error
file:///C:/Users/sp#7034/AppData/Roaming/Brackets/extensions/user/swmitra.html-designer/main.js 

Failed to load resource: net::ERR_FILE_NOT_FOUND
ErrorNotification.js:125 [Extension] failed to load C:/Users/sp#7034/AppData/Roaming/Brackets/extensions/user/swmitra.html-designer - Module does not exist: file:///C:/Users/sp#7034/AppData/Roaming/Brackets/extensions/user/swmitra.html-designer/main.jsErrorNotification.js:125 window.console.error
/LiveDevelopment/MultiBrowserImpl/transports/NodeSocketTransport.js:87 NodeSocketTransport - start
require.js:1903 GET file:///C:/Users/sp net::ERR_FILE_NOT_FOUND
ErrorNotification.js:125 [Extension] failed to load C:/Users/sp#7034/AppData/Roaming/Brackets/extensions/user/brackets-beautify - Module does not exist: file:///C:/Users/sp#7034/AppData/Roaming/Brackets/extensions/user/brackets-beautify/main.js
require.js:1903 GET file:///C:/Users/sp net::ERR_FILE_NOT_FOUND
ErrorNotification.js:125 [Extension] failed to load C:/Users/sp#7034/AppData/Roaming/Brackets/extensions/user/brackets-emmet - Module does not exist: file:///C:/Users/sp#7034/AppData/Roaming/Brackets/extensions/user/brackets-emmet/main.js

can somebody help me ?

**Comment by jpfux145** [comment]
19 days ago... and no comments.. :-(

**Comment by a-ignatov-parc** [comment]
Are you sure that you post this issue to correct repo? Brackets repo is [here](https://github.com/adobe/brackets) and i don't see any issues related to require.js except throwing errors about modules that can't be found in specified directory. But that is more problems with brackets/extensions and not with require.js

**Comment by jpfux145** [comment]
of course, I didn´t know how to create a correct issue.

thx.
