### ISSUE TITLE
r.js bundle specification too limited

### ISSUE THREAD

**Issue by cnshenj** [jrburke/requirejs#1383]
Scenario 1: I have two libraries lib1.js and lib2.js. They are independent but are almost always used. So I'd like to bundle them together. But r.js can only starts from module. I'd suggest when "include" is specified, the module name doesn't have to exist, it will be built from the modules included. For example: `modules: [{ name: "mylib", include: ["lib1", "lib2"] }]`. "mylib" doesn't exist, but it should be generated by r.js by including lib1.js and lib2.js.

Scenario 2: I don't want to do whole project optimization, but a few targeted optimization. Why can't I just use "out" for each module I want to optimize. For example:
```
modules: [
    {name: "lib", out: "lib-built"},
    {name: "fx", out: "fx-built"}
]
```

**Comment by jrburke** [comment]
Scenario 1: you can use [create: true](https://github.com/jrburke/r.js/blob/6f8d901eb5b168c067393fc2d67d1e68e272812a/build/example.build.js#L363) in that config block and r.js will create the file.

Scenario 2: the suggestion is to use a build script that drives two different builds. That script can share config if it is common, [here is an example of that approach](https://gist.github.com/jrburke/1509135).

Closing as a discussion ticket, feel free to continue discussion here.
