### ISSUE TITLE
skipDataMain and namespace build option

### ISSUE THREAD

**Issue by shariffy** [jrburke/requirejs#1384]
In order to load one script dependant on `requirejs` into another page that may or may not have its own version of `requirejs`, bundling in the lib file and namespacing seems to be the way to go. The issue is, on a page that uses `requirejs` with `data-main`, the bundled-in `requirejs` tries to load it too.

`skipDataMain` is meant to fill that purpose but where does one set it in this use case?

**Comment by jrburke** [comment]
That is a tricky one. Perhaps use [onBuildRead](http://www.ericfeminella.com/blog/2012/03/24/preprocessing-modules-with-requirejs-optimizer/) and when require.js is read, add a `var requires = { skipDataMain = true};` at the top of the file, and then hopefully that gets inside the namespace closure.

I have not tried it, but that should work. Going to close, but feel free to continue discussion here and we can reopen as necessary.
