### ISSUE TITLE
Using "Simplified CommonJS Wrapper" module format in minimized js file

### ISSUE THREAD

**Issue by asamushenkov** [jrburke/requirejs#1396]
Hello.

I faced the problem using "Simplified CommonJS Wrapper" module format in minimized js files. The issue is that first parameter was changed during optimization process, but regex looks for "require" token.

I think the best solution is to parse this token from the function declaration (same way) and then try to find dependencies.

Thank you.

**Comment by jrburke** [comment]
To avoid this issue, the files should be run through the r.js optimizer, which can normalize the define() calls to extract the dependencies as a dependency array. If the files are not part of a build layer, just modules dynamically loaded later, then depending on the build setup, these options can help:

* [skipDirOptimize](https://github.com/jrburke/r.js/blob/801bf683d3183171b8385950d00cd9894ed0b09b/build/example.build.js#L111)
* [normalizeDirDefines](https://github.com/jrburke/r.js/blob/801bf683d3183171b8385950d00cd9894ed0b09b/build/example.build.js#L132)

If I were to guess at the build setup, it might be enough to set normalizeDirDefines to "all" if doing a full project optimization (the build config has a "dir" setting in it).

Closing as a discussion ticket, but feel free to continue discussion here if more detail is needed, and we can reopen later if we identify a code change to do.

**Comment by asamushenkov** [comment]
We use requirejs in .NET MVC 4.5 project and for now it is not possible to use r.js optimizer. Bundles are created using Microsoft.AspNet.Web.Optimization framework.

Thank you for reply.

**Comment by jrburke** [comment]
Does the Microsoft.AspNet.Web.Optimization framework know how to properly inline define() calls in a file? At the very least it needs to be able to add the string ID as the first arg to the define() when multiple define() calls are used. If it is doing that, then I expect it would have some sort of option to also normalize the define() calls to extract the dependencies, to avoid the minification issue.

If it is not doing the string ID insertion, then the result is not going to work correctly anyway, regardless of the minification issue.

**Comment by asamushenkov** [comment]
No, it doesn't. We use this way to define a module:
```
define("foo/title", function (require) {
    require('my/cart');
    require('my/inventory');
});
```
Just a bit strange that logic is spreaded among r.js and requirejs. (I mean that some features of requirejs don't work without r.js optimizer).

Thanks for help. We will specify dependencies explicitly in module declaration.
