### ISSUE TITLE
req.createNode - Unused arguments: moduleName, url

### ISSUE THREAD

**Issue by aschyiel** [jrburke/requirejs#1397]
The req.createNode method doesn't seem to use the following arguments; Please consider removing them:
- moduleName
- url

https://github.com/jrburke/requirejs/blob/1b37e7dc8ea717ce4c2aeb4e89cb36b41e459d20/require.js#L1843

**Comment by jrburke** [comment]
The reason for having them there are [explained here](https://github.com/jrburke/requirejs/pull/1367#issuecomment-120552439)
