### ISSUE TITLE
window events removed after loading requirejs inside multi page app

### ISSUE THREAD

**Issue by mem0master** [jrburke/requirejs#1399]
is it normal that requireJs removeListeners from window object and do not reattach them afterward ? i checked the source code and it does not seem to do so.

PS : i am using requireJs inside a multi-page app, and it erase events attached to the window object by other js libraries

my current solution is as follow : 

```javascript
//main.js
var windowEvents = $._data( $(window)[0], "events" );
	
require([
		'jquery',
		'backbone',
		'someBackboneComponent',
], function ($, Backbone, someBackboneComponent) {
				
	$(function(){
	
		if (windowEvents) {
			for (var type in windowEvents) {
				for (var num in windowEvents[type]) {
					$(window).bind(type, windowEvents[type][num].handler);
				}
			}
		}

		//bootstrap app 
	});

});

```

**Comment by jrburke** [comment]
Right, in https://github.com/jrburke/requirejs/blob/master/require.js, it only calls removeEventListener for script nodes and passes in the methods it has registered. So I do not believe this is an issue, closing as a discussion ticket, feel free to continue discussion here.
