### ISSUE TITLE
RequireJS cannot load files with a hash (#) in their name

### ISSUE THREAD

**Issue by MarcelGerber** [jrburke/requirejs#1408]
(https://github.com/adobe/brackets/issues/11600)

In [Brackets](github.com/adobe/brackets), we `require` files directly from the user's AppData folder.
Normally, everything goes well, but now we have a case where the username includes a hash (`#`), so the path is something like `C:/Users/user#12345678/AppData/Roaming/Brackets/somefile.js`.
As the hash has a special meaning to the browser, this won't give us the result we want.

Is there anything we - or you - can do about this?

**Comment by petetnt** [comment]
I posted this to the ´brackets`-issue, but crossposting for future reference: Percentage encoding the hash with %23 works:

```
require(["foo%23bar.js"], function () {
    console.log("FOO");
});
```

**Comment by jrburke** [comment]
The encoding sounds correct, in URLs, the # is for a [fragment ID](https://en.wikipedia.org/wiki/Fragment_identifier), and not the path part in the URL. This is something enforced by the browser, not requirejs, so encoding it sounds like the right solution, so closing.
