### ISSUE TITLE
Mapping Node-Modules Doesn't Seem to Work

### ISSUE THREAD

**Issue by jtfairbank** [jrburke/requirejs#1411]
I have a logging module that is designed to work on web-app and any backend scripts we write for data processing / cleanup.  It has a dependency on Segment.io's javascript which is loaded through their CDN on the front-end using `paths`.

I'm using node for the backend scripts and downloaded Segement's node module through npm (https://segment.com/docs/libraries/node/quickstart/).

I setup a `map` from the include name on the backend since the node-module has a different name:

```
  map: {
   '*': {
      'segment': 'analytics-node'
    }
  }
```

I then get a error in r.js which seems to indicate that the `map` works for local modules but not for node modules.  Notice the different module names:

```
Error: Tried loading "analytics-node" at /foo/bar/analytics-node.js then tried node's require("segment") and it failed with error: Error: Cannot find module 'segment'
```

**Comment by jtfairbank** [comment]
Basically it is this issue: https://groups.google.com/forum/#!msg/requirejs/ur_UQLr04rc/sSpM8y87VNMJ

**Comment by jtfairbank** [comment]
Any word on this?

**Comment by jrburke** [comment]
Unfortunately there are limits to what can be supported when trying to also integrate with node's rules for require integration. Using the suggestion in that email list thread of defining the module up front under the correct ID by loading it from the node location is the way to go.

**Comment by jtfairbank** [comment]
@jrburke Sure thing.  Maybe you could add that solution to the require.js documentation in the [Use with Node](http://requirejs.org/docs/node.html) page and with a note that links to the right section in the [Map API section](http://requirejs.org/docs/api.html#config-map)?

**Comment by jrburke** [comment]
I added a note about it in this section:
http://requirejs.org/docs/node.html#2

**Comment by jtfairbank** [comment]
Looks good.  I'd still add in a code example or a link to the email thread, since most people will be left asking "ok how do I get around this".  But honestly up to you.
