### ISSUE TITLE
file: protocol not supported - Suggestion: Improve error message

### ISSUE THREAD

**Issue by SetTrend** [jrburke/requirejs#1414]
I've been working here and wondering for quite some time what may have caused this cryptical RequireJS to occur. Then after some time of digging and debugging I learned that the file: protocol isn't supported by RequireJS.

I'd like to suggest to improve the way exceptions are raised by RequireJS. It should get clear from the error message what's been the cause for an error.

**Comment by jrburke** [comment]
The file: protocol should work fine, but it is subject to the rules set in place by the browser for any URLs used in script tags, or if using a loader plugin that uses XMLHttpRequest, the rules for XMLHttpRequest usage for file: documents, which are fairly severe.

Unfortunately the rules seem to be a bit different across browsers, and I expect them to change over time, so I do not think it makes sense to add code to try to infer when they might fail inside requirejs to give errors on their use.

Perhaps a note in the docs, but it would require a finding a resource on the net that has the set of restrictions from browsers listed out. Not sure what that would be, but a new ticket could be opened if it is found, with a doc change for it.
