### ISSUE TITLE
Intended behavior?

### ISSUE THREAD

**Issue by SomethingSexy** [jrburke/requirejs#1416]
I am almost positive this is the intended behavior but just want to run this past someone to make sure and maybe someone knows of a way to handle this.

Say I have a package called store, structured like this:
- scripts
    - store
        - main.js
        - shelf
            - food.js

In code I can do this

    require(['store'], function(store){});
    require(['store/shelf/food'], function(food){});

This is all dandy.

However, say that the store package is pre-optimized already.  So the entire package has now been compiled into dist/store/main.js.  The shelf/food.js file doesn't exist as a standalone file anymore.

New structure looks like this and the package configuration has been updated to pull from the dist folder instead of scripts.
- dist
    - store
        - main.js

Running this works as intended still

    require(['store'], function(store){});

However, running this by itself does not work, as it is still trying to find the path location (dist/store/shelf/food.js)

    require(['store/shelf/food'], function(food){});

If I were to do this

    require(['require', 'store'], function(require, store){
        require(['store/shelf/food'], function(food){});
    });

This now works because store was loaded, which contains the module 'store/shelf/food'.

I definitely don't want to do that.  At this point, these seem like my only two options:

1. Don't run off the pre-optimized package, run from the source.  When you optimize your entire application it will get optimized anyway.
2. Manually include the module you need in the paths config. 
```
    paths: {
        'store/shelf/food': '../dist/store/main'
    }
```

Are those my two options, any others? Or am I doing something wrong.

**Comment by jrburke** [comment]
Use [bundles config](http://requirejs.org/docs/api.html#config-bundles) instead of paths config, that should work better.

Closing as a bundles config should be enough for this issue. Feel free to continue discussion here though.

**Comment by SomethingSexy** [comment]
Ya that will definitely be cleaner than have to setup a path for each one that is needed.
