### ISSUE TITLE
How can I have RequireJS Optimizer optimize a library into a single file?

### ISSUE THREAD

**Issue by SetTrend** [jrburke/requirejs#1418]
I have created a library from a number of TypeScript files.

The TypeScript compiler is creating a JavaScript file for each of the TypeScript modules. Having the AMD option set, they are created in RequireJS format, i.e. using define() to define their content.

Now I want the RequireJS optimizer to create one single, minimized JavaScript file from all these module files.

There is no *main* file serving as something like a dependency tree root. I just want to have them all included in the resulting Optimizer output file without exception, so at runtime all of them are available from that file, no matter which options/types the user will choose to use.

Which configuration do I need to provide to RequireJS optimizer to achieve this?

Your help is appreciated.

Here's a file tree, resembling the library structure I'm using:

```
-- [Scripts]
   \-- jquery-2.1.4.min.js
   \-- require.js
-- [TypeScript]
   \-- [Special]
       \-- Module1.js  (*)
       \-- Module1.js  (*)
   \-- Module1.js  (*)
   \-- Module2.js  (*)
   \-- Module3.js  (*)
```
I have marked the JavaScript files to be appended to the Optimizer output file with an asterisk.

**Comment by SetTrend** [comment]
Anything new regarding this issue?

**Comment by ryanshawty** [comment]
Would not running a concatenation tools such grunt-contrib-concat do what you are looking for?

**Comment by SetTrend** [comment]
Unfortunately, no. Because the RequireJS Optimizer adds a name to each of the modules when concatenating, which is a mandatory prerequisite for finding the joined modules in the file.

Modules usually are generated without a module name, because it can be computed from the file name. But with concatenated modules in one single file this option lapses.

**Comment by jrburke** [comment]
You can use the r.js optimizer to build the modules using the [almond](https://github.com/jrburke/almond) AMD API provider, or using one of the smaller [other API providers](https://github.com/jrburke/requirejs/wiki/AMD-API-Shims), but there is no built in support for stripping out the define calls for example and creating a simpler structure underneath. That cannot be done in a generic way, but may be possible depending on how limited the use of the AMD APIs are. You could look at using the [onBuildWrite hook](http://www.ericfeminella.com/blog/2012/03/24/preprocessing-modules-with-requirejs-optimizer/) to do that manual transformation yourself if the use case was simple enough.

That is the extent of the capabilities though, no plans to add other options.
