### ISSUE TITLE
unexpected result calling optimise from the out function of a running optimisation

### ISSUE THREAD

**Issue by ogim** [jrburke/requirejs#1419]
I have a project with a webworker part and a primary part, both sharing each others libraries. I want to optimize both and combine them into one file. 

For that I optimize the worker and in the out function i call the optimisation of the primary and pass the result of the worker.

What I notice is that the optimisation of the primary does not contain the libraries which are also used in the worker optimisation. because the optimisation of the worker is in fact finished I dont expect that to happen. Probably the optimiser is reset after the out function is finished. 

Wouldn't it be more logical to reset just before out is called ?

My script is something like this:
```
function optimize(config){
	requirejs.optimize(config, function (buildResponse) {
		console.log("\nproject built in " + config.out + ' :');
		console.log(buildResponse);
	}, function(err) {
		console.log("\nerror creating build !");
		console.log(err);
	});
}
function createWorker(callback){
	optimize({
		"baseUrl": "js",
                "include":["myConsts"],
                "...":"...",
		"out":function (text, sourceMapText) {
			callback(text);
                }
	});
}
function createPrimary(workerScript){
	optimize({
		"baseUrl": "js",
                "include":["myConsts"],
                "...":"...",
		"out":function (text, sourceMapText) {
			writeFile("bin/myProject.js", text);
                },
                "onBuildRead": function onBuildRead(name, path, contents) {
                        if(name==="almond"){
                             contents = "\n" + workerScript + contents + "\n";
                        }
                        return contents;
                }
	});
}
createWorker(createPrimary);
```

**Comment by jrburke** [comment]
I expect it works better by triggering the second build as part of the requirejs.optimize() callback, that will allow the optimizer to reset, and triggering of the callback to optimize is the formal end point for the optimization. For that reason, the out callback cannot be the final step. It should be fine though to just doe the primary trigger in the optimize callback.
