### ISSUE TITLE
r.js - static analysis - not capturing nested requires - need a workaround

### ISSUE THREAD

**Issue by ORESoftware** [jrburke/requirejs#1420]
According to my experience, the r.js optimizer does not capture nested 'require's like so:

```javascript
require(['one'],function(){

  require(['two'], function(){
      //two will not be included by r.js in the optimized output
  });

});
```
likewise:

```javascript
define(['one'],function(){

  require(['two'], function(){
      //two will not be included by r.js in the optimized output
  });

});
```

up until now I have been able to deal with this, organizing my files so that the r.js optimizer can see all of them during its static analysis. But now I have a problem - I removed all module references to Backbone, and would like to only depend on the global Backbone instance - window.Backbone - in every module. This pretty much means that Backbone needs to load before anything else.

However, the requirement of loading Backbone before anything else seems to butt heads with the requirement of organizing things so that r.js sees them.

In other words, the only way I know of getting Backbone to load first would be to use nested requires - which r.js can't work with (as far as I know.)

here is my real life main.js config file:

```javascript
    requirejs.config({
        enforceDefine: false,
        waitSeconds: 7,
        baseUrl: '/static',
        paths: {
            'async': 'vendor/async',
            'jquery': 'vendor/jquery',
            'ejs': 'vendor/ejs',
            'flux': 'vendor/Flux',
            'text': 'vendor/text',
            'form2js': 'vendor/form2js',
            'underscore': 'vendor/underscore-min',
            'backbone': 'vendor/backbone',
            'bootstrap': 'vendor/bootstrap',
            'react': 'vendor/react-with-addons',
            '#hotReloader': 'app/js/hot-reloading/hotReloader',
            'socketio': 'vendor/socketio',
            '#Adhesive': 'app/js/adhesive/Adhesive',
            '#jsPatches': 'app/js/patches/jsPatches',
            '#backbonePatches': 'app/js/patches/backbonePatches',
            '#windowPatches': 'app/js/patches/windowPatches',
            '#allTemplates': 'app/js/meta/allTemplates',
            '#allViews': 'app/js/meta/allViews',
            '#allModels': 'app/js/meta/allModels',
            '#allCollections': 'app/js/meta/allCollections',
            '#appState': 'app/js/state/appState',
            '#viewState': 'app/js/state/viewState',
            '#allControllers': 'app/js/meta/allControllers',
            '#allDispatchers': 'app/js/meta/allDispatchers',
            '#BaseCollection': 'app/js/collections/BaseCollection',
            '@AppDispatcher': 'app/js/flux/dispatcher/AppDispatcher',
            '#allCSS': 'app/js/meta/allCSS',
            '#allFluxActions': 'app/js/meta/allFluxActions',
            '#allFluxConstants': 'app/js/meta/allFluxConstants',
            '#SuperController': 'app/js/controllers/SuperController',
            '@Router': 'app/js/routers/router'
        },

        'shim': {

            '@Application': { 
                'deps': ['backbone']   //unfortunately this doesn't hurt or help the situation
            },

            'underscore': {
                'exports': '_'
            },

            'backbone': {
                'deps': ['jquery', 'underscore'],
                'exports': 'Backbone'
            },

            ejs: {
                exports: "ejs"
            }
        }

    });

     require(['app/js/application'], function (Application) {
        
          Application.start();

      });

```

so, r.js will work as this is configured and trace the dependencies correctly, *BUT* what I really really really need is for Backbone to be loaded before app/js/application. so what I need is this:

```javascript
      require(['backbone'], function (Backbone) {
        
                require(['app/js/application'], function (Application) {
        
                 Application.start();

                });

        });
```

but r.js doesn't work with the above! :(

what can I do? thanks for your help!!!

**Comment by ORESoftware** [comment]
I believe the way to solve this is like so:


```
({
    "preserveLicenseComments": false,
    "baseUrl": "../public/static",
    "name": "app/js/main",
    "mainConfigFile": "../public/static/app/js/main.js",
    "out": "../public/static/app/optimized/optimized.js",
    "paths" :{
        requireLib : 'vendor/require',
        jqueryUI: "empty:",
        jqueryUI_CSS: "empty:"
    },

    "include": ['requireLib','app/js/application'],   ///<<< look here
    "stubModules":['text']

})
```

this seems to do the trick, r.js traces the dependencies correctly now - if this is the best way to do it, please let me know, thanks

**Comment by jrburke** [comment]
For nested require calls, if you do want the parser to see them, use [findNestedDependencies: true](https://github.com/jrburke/r.js/blob/2fdfddd959f371b775027c0145b00aed334a58f6/build/example.build.js#L339). The other option is to explicitly list them in the include array as you show. That approach works well if they do not change that often and you still want to get some dynamic loading via the nested require([]) calls to cut down on initial payload size.

Closing as a discussion ticket, there are mechanisms to get the nested dependencies.

**Comment by ORESoftware** [comment]
thanks for the info, I obviously didn't know about "findNestedDependencies", good stuff
