### ISSUE TITLE
errback - special case - invoke if file is not already cached

### ISSUE THREAD

**Issue by ORESoftware** [jrburke/requirejs#1421]
I have this route that invokes a function in a controller based off different URLs

```javascript
   controllerRoute: function (controllerName, actionName, id) {
                var self = this;
                require(['app/js/controllers/all/' + controllerName], function (cntr) {
                        if (typeof cntr[actionName] === 'function') {
                            cntr[actionName](id, self.changeView);
                        }
                        else {
                            cntr['default'](id, self.changeView);
                        }
                    },
                    function (err) {
                        //route was not found, need to take another action
                        console.error('route was not found' + String(err));
                    });
            },
```

as you can probably tell, I dynamically invoke a particular controller given a different URL - standard stuff - but my question / request to you is -

I want to invoke the errback if the require'd file is not in the cache - in other words - I don't want requirejs to go looking on the server for the file - I want RequireJS or this particular function call to be configured so that it immediately fires the errback if the file is not in the cache - is this available / possible somehow?

thanks

**Comment by noahpeters** [comment]
you could test in advance requrejs.defined("module-path"), no?

**Comment by ORESoftware** [comment]
thanks @noahpeters I will try that

**Comment by jrburke** [comment]
requirejs.defined will return true if it is already in the cache, but does not handle the case where it might be requested. It sounds like the desire was to know if it is in the module export cache, so that should be enough, so closing.

**Comment by ORESoftware** [comment]
yeah that's plenty good thanks
