### ISSUE TITLE
using constants in dependencies array

### ISSUE THREAD

**Issue by ORESoftware** [jrburke/requirejs#1428]
@jrburke 

It would be cool to use constant values in my AMD dependency arrays like so:

```javascript
define([
        '+appState',
        '#allCollections',
        'ejs',
        'underscore',
        '#Adhesive',
        'react',
        'app/js/jsx/reactComponents/JobsList',
        appConstants.REACT_VIEW_BASE + 'JobsList',   //see here
        'require'
    ])
```

this works fine in development, but in production it looks like the optimizer outputs the correct output, but what happens is that once it's loaded in the browser, it goes looking for the literal 'xxx/zzz/JobsList' but in the optimized output there is only appConstants.REACT_VIEW_BASE + 'JobsList', so it can't make the match, and then goes looking on the filesystem. Do you follow?

Is there a fancy way to make this work easily? Right now the constants are in their own AMD module like so:

```javascript
define(function(){

    return Object.freeze({

        'STANDARD_VIEW_BASE': 'app/js/jsx/allStandardViews/',
        'REACT_VIEW_BASE': 'app/js/jsx/reactComponents/',
        'CONTROLLER_VIEW_BASE': 'app/js/jsx/controllerViews/',
        'REL_VIEW_BASE': 'app/js/jsx/relViews/',
        'COLLECTIONS_BASE': 'app/js/collections/',
        'MODELS_BASE': 'app/js/models/'


    });
});
```

but instead of having the constants in their own AMD module I was thinking I could potentially put the constants in requirejs.config({}) and then requirejs could resolve it somehow? is this possible or should I abandon this idea of using some constants values in the dependency array?

**Comment by ORESoftware** [comment]
so it might become:

requirejs.config({

paths: {
        'STANDARD_VIEW_BASE': 'app/js/jsx/allStandardViews/',
        'REACT_VIEW_BASE': 'app/js/jsx/reactComponents/',
        'CONTROLLER_VIEW_BASE': 'app/js/jsx/controllerViews/',
        'REL_VIEW_BASE': 'app/js/jsx/relViews/',
        'COLLECTIONS_BASE': 'app/js/collections/',
        'MODELS_BASE': 'app/js/models/'
}

});

I don't think this will work for two reasons -

(1) I need to concatenate the paths above with a token like  define(['STANDARD_VIEW_BASE' + 'SomeView']) which won't work

(2) I also want to refer to the contants in the code, not just in the dependency array, so that would be double the effort

Any ideas would be appreciated, thanks

**Comment by ORESoftware** [comment]
the only way I can think of making it work is feeding the optimized output with the appConstants values somehow

**Comment by jrburke** [comment]
Dependency IDs need to be string literals for tracing and portability to work: relying on globals for the IDs is an antipattern for encapsulated modules. Instead, favor using [maps config](http://requirejs.org/docs/api.html#config-map) or [paths config](http://requirejs.org/docs/api.html#config-paths) to direct a particular ID to another concrete provider for the ID.

Example using paths:

```javascript
requirejs.config({
  paths: {
    ''STANDARD_VIEW_BASE': 'app/js/jsx/allStandardViews'
  }
});

// then in module:
define(['STANDARD_VIEW_BASE/JobsList'], ...);
```
