### ISSUE TITLE
TimeOut after optimize the files

### ISSUE THREAD

**Issue by gsantome** [jrburke/requirejs#1430]
Hello, I'm having an important error and I can't find a solution and i don't want to change to web pack because i love requirejs... 
I'm optimizing the files because I have a lot of files and I need to load everything from the begging... the problem here is after i create the main.js with all of my files inside... im getting load timeout from require js... and this is because waitSeconds lives inside my requirejs configuration... but im not loading that configuration from html... im just loading the optimized file... 

Thanks!

**Comment by jrburke** [comment]
Is the timeout happening while r.js is running? If so, you can set `waitSeconds: 0` if you want to disable the timeout during a build. I filed jrburke/r.js#872 to just automatically set the waitSeconds to 0 for a build.

If it is after a build, then updating the requirejs.config after a build to be waitSeconds: 0 in the HTML file will disable it.
