### ISSUE TITLE
Path fallback is not working in some cases

### ISSUE THREAD

**Issue by kpym** [jrburke/requirejs#1433]
The path fallback works fine in this case : 

    requirejs.config({
        paths: {
            angular: [
              'https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.7/angular.min',
              'https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.min',
              'libs/angular.min'
            ]
        }
    });

    require(['angular']);

but this one is not working : 

    requirejs.config({
        paths: {
            angular: [
              'https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.7',
              'https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7',
              'libs'
            ]
        }
    });

    require(['angular/angular.min']);

if the first one `https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.7/angular.min` fails, requirejs is not looking for the two other alternatives.

**Comment by jrburke** [comment]
Unfortunately the paths fallback feature is restricted to [exact module ID matches](http://requirejs.org/docs/api.html#pathsfallbacks). No plans to complicate the logic to allow prefix matching.

**Comment by kpym** [comment]
This is not a good news for libraries that have plenty of modules in separate files like angular 2. Now we have to define alternative paths for any separate module ... copy/paste is our friend ;)
