### ISSUE TITLE
how can i require existing named  module  in reqiure( 'module name' ) style?

### ISSUE THREAD

**Issue by elvinzhu** [jrburke/requirejs#1434]
hi , i have a few named modules and requrejs combined into one file, so i am very sure that those module are existing when i need to `require` them. But it seems that i can not `require( 'module name' )` them without `require( ['module name'] )` first.

**Comment by sergeylukin** [comment]
I guess require('module name') is only available when CommonJS wrapper is used, i.e. inside module definition:

```
define(function (require) {
    var foo = require('MODULE_NAME');
    ...
});
```

while outside of module definition you would use RequireJS implementation of `require` method which expects an array of modules:

```
require(['MODULE_NAME']);
```

Hope that helps.

**Comment by jcrben** [comment]
See http://requirejs.org/docs/whyamd.html#sugar for more details.

I think this could be closed.
