### ISSUE TITLE
Optimizer: namespacing captures inner require

### ISSUE THREAD

**Issue by herby** [jrburke/requirejs#1438]
AFAICT, `namespace` attribute should only rename `define` and `require` in the root level, but not in this case:

```js
define(["require"], function (require) {
  //...
  require(["module/id"], ...);
  // ...
});
```

But it does capture this `require` as well. In majority of cases it does not create harm, but there are cases which rely on `require` being the local require, not the root `namespace.require` (workaround - use different variable name).

**Comment by jrburke** [comment]
Definitely a weakness in the namespace support. Since the work will happen in r.js, and is likely not a 2.x issue, filed jrburke/r.js#871, which would fix this bug, will be hard to do before that change. So closing this one in favor of tracking it in the other bug.
