### ISSUE TITLE
"Shim config not supported in Node, may or may not work."

### ISSUE THREAD

**Issue by mt406** [jrburke/requirejs#1443]
I am working on a project which works fine on browser , now we are trying to run it on server side using nodejs.

I have below configurations : 
node : v4.2.1
npm :  v2.14.7

and when I am trying to run my project on nodejs , getting the error as :  
" Shim config not supported in Node, may or may not work"

Since the modules and dependencies (AMD) are working fine on browser I assume the shims config are correct .

Please let me know if I am missing something ?

Regards
Manish

**Comment by jrburke** [comment]
Shim config is for scripts that do not use a module API, so they likely try to bind to the browser global. However, the global rules in Node are different, so they will likely have problems, not be defined in the right way or see things they assume will be on the global object.

This is just a hard restriction for shimmed scripts, best to use modules calling a module API when in node.
