### ISSUE TITLE
How to check version of requirejs ?

### ISSUE THREAD

**Issue by mt406** [jrburke/requirejs#1444]
I need to check version of requirejs from npm so for that I used the command 
"npm version requirejs"
and it is giving the error : 

" npm ERR! version No valid package.json found
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "version" "requirejs"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7

npm ERR! Unexpected token u
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\INTDemoOnNode\tutorials\welllog\curve\js\npm-debug.log"

When I check package.json of requirejs the version is "version": "2.1.20",.

Please tell me if I am missing something ?

Regards
Manish

**Comment by jcrben** [comment]
`npm version` does not give you the version number of packages. See https://docs.npmjs.com/cli/version

`npm ls --depth=0` will list installed packages. If you're really worried about package.json being incorrect, I suppose you can dive into the node_modules and compare the source code there to the repo.

This should be closed.
