### ISSUE TITLE
data-main attribute on <script> tag that doesn't load require.js works

### ISSUE THREAD

**Issue by laupkram** [jrburke/requirejs#1447]
I did somewhat an accident discovery that I was able to load my data-main js file in a file that doesn't load requireJS
```
<script type="text/javascript" src="requirejs.config.js" data-main="theme.js"></script>
<script type="text/javascript" src="requirejs.js"></script>
```

and it perfectly loads my theme.js file

is this an intentional feature of requirejs? or a bug?

I hope this isn't a bug.

the contents of my requirejs.config.js are below

```
var require = {
    baseUrl: '/js/',
    paths: {
        'jquery': "lib/jquery/jquery",
        'bootstrap': "lib/bootstrap/js/bootstrap"
    },
    shim: {
        'bootstrap': ['jquery']
    },
    map: {
        '*': {
            'jquery': 'jQueryNoConflict'
        },
        'jQueryNoConflict': {
            'jquery': 'jquery'
        }
    }
}
```

**Comment by jrburke** [comment]
It is the result of the behavior here:

https://github.com/jrburke/requirejs/blob/edd2f929212a717caf47b27dab2575c4d3bed48c/require.js#L1967

I could see trying to restrict that behavior in the future, to just the tag that was used to load require.js, particularly if [document.currentScript](https://developer.mozilla.org/en-US/docs/Web/API/Document/currentScript) was reliable across browsers. However, I do not expect it to change for the 2.1.x series of requirejs.

To avoid the data-main scanning, setting [skipDataMain](http://requirejs.org/docs/api.html#config-skipDataMain) to true in the config will stop it.

Closing as this seems to be a question/discussion ticket, but feel free to continue discussion here, and we can reopen if a change needs to be done.
