### ISSUE TITLE
invalid package.json

### ISSUE THREAD

**Issue by n00dl3** [jrburke/requirejs#1454]
Would it be possible to change for a valid package.json (at least with a version) so people (like me) using npm  as front-end package manager could install requirejs ?

**Comment by jrburke** [comment]
requirejs is published to the npm registry, and the structure of that published package is managed by the https://github.com/requirejs/requirejs-npm repo, so closing as this is not the primary repo for npm consumption. Feel free to continue discussion here though if that does not fit your needs.

**Comment by n00dl3** [comment]
thanks I wasted 2 hours looking for this!!!
