### ISSUE TITLE
Nested dependencies randomly don't load

### ISSUE THREAD

**Issue by dudewad** [jrburke/requirejs#1457]
I don't have a complex dependency tree, but I do have third-party dependencies in my main.js file that have other third party dependencies.

Unless I add the dependencies of these first-degree dependencies to my main.js file, I get random failure to load either the first-degree or the second-degree dependencies, more often on an empty cache. Here is an example:

RequireMain.js:
```javascript
require.config({
	baseUrl: "script/module",
	enforceDefine: true,
	paths: {
		signals: "vendor/signals"
	}
});

define(["main"]);
```

main.js:

```javascript
define(
	["signals", "vendor/crossroads", "vendor/preloadjs", "router"],
	function (signals, crossroads, createjs, router) {
		//At this point all controllers should be loaded and ready to go
		//Random failures are "signals" and "crossroads" if I don't include them as dependencies here
		return {};
	}
);
```

The important thing to note in my main.js file is that the [vendor/crossroads] and [signals] dependencies are not required or used in the main.js module. They're used in router and preloadjs, respectively. Both modules properly define their dependencies yet fail to load them consistently.

I've tried every combination of shim configs I can think of. There are not external scripts causing issues (I removed everything and still reproduce the problem). I'm using data-main to load my requireMain.js file.

All third party files have module definitions except for js-signals, which I wrapped in a define call and that seems to "fix" it, at least to the point where now it only breaks randomly instead of consistently every time.

Not sure what the deal is, wondering if this is just a case of me misinterpreting the docs.

**Comment by jrburke** [comment]
What are the errors that are emitted? If you have a small test project that just includes the scripts in question with the HTML with just a script tag for require.js w/data-main and the two scripts above, someone here should be able to pull it down and figure out the disconnect.

It does sound like some dependency relationship issue: either the sub-dependencies are not expressing their dependencies correctly or the top level dependencies are not specifying the dependencies in a way require.js can parse. Hard to know without looking at the specific scripts in play and how they loaded by require.js though.

**Comment by dudewad** [comment]
Turns out I won't have time to address this issue, I'm on a pretty tight schedule. If I do get time to work on it I'll let you know. Sorry about that.
