### ISSUE TITLE
Uncaught exception in require.js

### ISSUE THREAD

**Issue by busylee999** [jrburke/requirejs#1467]
Hi, I have errorception in my website. It handle next exception from website

<code>
Error: Script error for: main
http://require.org/docs/errors.html#scripterror
at Error (native)
at C (http://partner.ellada-an.com/js/libs/require/require.js:8:252)
at HTMLScriptElement.i.onScriptError (http://partner.ellada-an.com/js/libs/require/require.js:30:59)</code>

Have you any ideas?

**Comment by jrburke** [comment]
It could be a a non-HTTP 200 script fetch request, error in fetching, or maybe a parse error. Hopefully the Network or Resources tab in the browser's developer tools would give insight into if it is an HTTP error (if so, requirejs cannot see those errors directly, those are not reported to script tags). If a parse error, there is hopefully another error in the web console with the details of the error.

Closing as a discussion ticket, feel free to continue discussion here.
