### ISSUE TITLE
sessionStorage error on  mobile phone(MI3)

### ISSUE THREAD

**Issue by calmchang** [jrburke/requirejs#1471]
1.we have 2 html ,  A.html and B.html
2.use requirejs  
3.at A.html ,when dom ready, do code
    sessionStorage.setItem('test','123);
    location.href ='B.html';
4.at B.html , when dom ready,do code
   var temp = sessionStorage.getItem('test');
   alert(temp);// error, now ,result is null

this error just happend on  browser of mi3(mobile phone)  

<img  src='http://d.hiphotos.baidu.com/baike/c0%3Dbaike116%2C5%2C5%2C116%2C38/sign=f8fbe36c0cb30f242197e451a9fcba26/cefc1e178a82b901c9e28b3e708da9773912ef74.jpg'>

**Comment by jrburke** [comment]
I don't believe this is an issue with requirejs: it does not tamper with sessionStorage, and I expect is a race condition inside the browser with doing the final save to session storage before that page is wiped and navigation goes to the second page.

**Comment by calmchang** [comment]
But if I don`t use requrejs ， sessionStorage can be saved when goes to second page , it`s so  strange
