### ISSUE TITLE
RequireJS and Adobe DTM

### ISSUE THREAD

**Issue by ntw-phazard** [jrburke/requirejs#1484]
Hi everybody,
I'm using Adobe DTM to dynamically load my tags and requireJS.

According to Adobe's guide, I'have to add these line on my HTML pages.
```HTML
<script src="/js/digitalData.js" type="text/javascript"></script>
<script>dataLayer.setEnvironment('XXfrdev'); </script>
<script>dataLayer.setPage ("index.html",'','',false,'','');</script>
<script src="//assets.adobedtm.com/XXXXXX/satelliteLib-XXXXX-staging.js"></script>
<script>_satellite.pageBottom();</script>
```

This line
```HTML
<script src="//assets.adobedtm.com/XXXXXX/satelliteLib-XXXXX-staging.js"></script>
```
must be placed before the head tag like this:
```HTML
<script src="//assets.adobedtm.com/XXXXXX/satelliteLib-XXXXX-staging.js"></script>
</head>
```

And then, the line
```HTML
<script>_satellite.pageBottom();</script>
```
must be placed before the body tag :
```HTML
<script>_satellite.pageBottom();</script>
</body>
```

With a simple HTML page, it's works but my website using the requirejs plugin and these error appear

"Mismatched anonymous define() modules". Indeed, in the js file "http://assets.adobedtm.com/XXXXXX/satelliteLib-XXXXX-staging.js" there is a call to "define" function. So, I tried to use define/require function to load the script on my website.

```Javascript
require.config({
  paths: {
    digitalData: "/js/digitalData",
    devtagslink: "//assets.adobedtm.com/XXXXX/satelliteLib-XXXXX-staging",
  },
  shim: {
    devtagslink: {
      deps: ["digitalData"]
    }
  }
});

require(['devtagslink'], function(devtagslink){ 

  dataLayer.setEnvironment('XXfrdev');
  dataLayer.setPage("index.html",'','',false,'','');
  _satellite.pageBottom();
  /*$('#script_test').html("_satellite.pageBottom();");*/
  /*alert(_satellite);*/

});
```

ANd I've this error : "ReferenceError: _satellite is not defined" from the "//assets.adobedtm.com/XXXXX/satelliteLib-XXXXX-staging" file. Does anything is wrong with my requireJS code ?

**Comment by jrburke** [comment]
If the error is from the `  _satellite.pageBottom();` line in the require([]) callback, maybe `devtagslink.pageBottom()` works instead? However if the error is in the -staging file, then it may be a malformed file, in that they probably should not have an unnamed define in there if they want to support AMD loading. You could side-step the issue by loading requirejs after the staging file:

```javascript
<head>
<script src="/js/digitalData.js" type="text/javascript"></script>
<script>dataLayer.setEnvironment('XXfrdev'); </script>
<script>dataLayer.setPage ("index.html",'','',false,'','');</script>
<script src="//assets.adobedtm.com/XXXXXX/satelliteLib-XXXXX-staging.js"></script>

<script src="require.js"></script>
</head>

<!-- later in the HTML -->
<script>_satellite.pageBottom();</script>
```

Closing as a discussion issue, feel free to continue discussion here though.

**Comment by likesjx** [comment]
Also, DTM does it's own file loading. Which is where the Mismatched error probably comes from.
