### ISSUE TITLE
Question about requirejs functionality

### ISSUE THREAD

**Issue by enkitosh** [jrburke/requirejs#1487]
Hi there. Heads up this is not an issue, I just did not know where to ask other than here.
First off I want to say thank you for creating this amazing library. I have been using it for years now and I cannot believe that it's still the only module loader that does not require a build step, well done :)

My question concerns module reuse. I'm unsure of what happens when I register my modules.
I will demonstrate with code. Say I have this base html page

    <!DOCTYPE html>
    <html>
        <head> some head stuff </head>
        <body>
             
             <script src="/static/bower_components/requirejs/require.js" data-main="/static/js/config"></script>
             <script>
                require(['config'], function(Config) {
                    require(['someModule'], function(SomeModule) {
                        SomeModule.init();
                    }
                }
             </script>
         </body
    </html>

I use a template language, or that is to say I'm working in the django framework so using their template language I can make html snippets and include them here and there. 
What I'm wondering is that I want to be able to make template snippets that depend solely on themselves, that is they include css/html/javascript themselves.
Consider the following template

    {% extends 'base.html' %}  <== Base template were we initially load requirejs config
    {% block content %}
    <div id="someveryfinediv"></div>
    <script src="/static/bower_components/requirejs/require.js" data-main="/static/js/config"></script>
             <script>
                require(['config'], function(Config) {
                    require(['anotherModule'], function(AnotherModule) {
                        AnotherModule.init('#someveryfinediv');
                    }
                }
             </script>

This way the template can be included into other templates without the need to additionally specify static dependencies for that template.

My question is this, when I do this I load requirejs config two times. Does this mean that identical configs are loaded two times or does requirejs recognize that config is already loaded and so it passes on the instance of that config?

Thank you :)

**Comment by jrburke** [comment]
requirejs will only do one fetch for 'config', and will use the same defined module export when passing it to the require callback.

Closing as a discussion ticket, feel free to continue discussion here.

**Comment by enkitosh** [comment]
Thank you @jrburke for your answer :+1:
