### ISSUE TITLE
RequireJS :: depMaps Bug (really?) fixed

### ISSUE THREAD

**Issue by Loopshape** [jrburke/requirejs#1491]
Hello to all Javascript developers, 

I'm using RequireJS to assemble my javascript-files into a dependency que. Unfortunately, I've got an error-message from the RequireJS script, that the "depMaps were not defined".
So I've started to check that RequireJS file and wrote a small fix for it. I don't know, if this solution is ok or something could really screw up...

You can download the script with following URL (with comments):
> http://requirejs.org/docs/release/2.1.22/comments/require.js

Around the line #767, there's something written like that:
> this.depMaps = depMaps && depMaps.slice(0);

My fix is just an extended version of that line:
> this.depMaps = depMaps===undefined ? this.depMaps : depMaps || depMaps.slice(0);

The error message has gone so far, which was really annoying and I couldn't find a solution for it in the web.
If something is wrong, then please tell me and I'll try to get a workaround for it.

Thanks to J. Burke for this great tool...

Bye!

#javascript #requirejs #script #dependency #loader #que #management #bugfix #module #workaround﻿

**Comment by jrburke** [comment]
Do you have a test case that illustrates the problem? That way if there is a code change to requirejs to address it, I can create a unit test to make sure it does not break in the future.

**Comment by Loopshape** [comment]
Hello Mr. Burke, 

I changed the RequireJS-script back to the original state with the one-liner, that was giving me a message about "depMaps not defined". But I can't reproduce the error after a few days, now. 
Maybe a cache related thing or something else with the Javascript engine of my Firefox browser was the problem. Sometimes addons or plugins for some browsers could make these error- or warning-messages. Your script runs smooth and normal as expected. So this issue can be closed. 
Thank you for your attention. 

Kind regards, 
Arjuna
