### ISSUE TITLE
Optimizer and context configuration

### ISSUE THREAD

**Issue by mazerte** [jrburke/requirejs#704]
Hi,

I work for a project where a use RequireJS for dependencies and optimization.
I create two require context one for my app and an other for unit-test.

When a build my project (with mainConfigFile configuration), I have this error:

```
//Do final input verification
        if (config.context) {
            throw new Error('The build argument "context" is not supported' +
                            ' in a build. It should only be used in web' +
                            ' pages.');
        }
```

Ok, I can't build with a context configuration.

I try too overload context properties in my grunt fille
```
context: null
mainConfigFile: 'js/main.js'
```
It doesn't work

I try too create un config variable in my main file
```
var requirejsConfig = {
    shim: ...
    paths: ...
    modules: ...
}

if(is_test) {
    requirejsConfig.context = 'app';
}
requirejs.config(requirejsConfig)
```
It doesn't work

And I try a dynamic configuration
```
requirejs.config({
    contest: is_test ? 'app' : null,
    shim: ...
    paths: ...
    modules: ...
});
```
It doesn't work too ...

I try to find the way for work with optimizer and my test unit implementation without duplicate my main file or a build file

Thank for your help.
Mäzèrté

**Comment by twizzyyanki** [comment]
i don't understand this solution. Could someone kindly elaborate more?

**Comment by baldwicc** [comment]
Found that this error also gets thrown when context is set to ``undefined`` - setting it to ``null`` seems to work fine.
