### ISSUE TITLE
Configuring via window.require doesn't work with namespaces

### ISSUE THREAD

**Issue by ianb** [jrburke/requirejs#815]
You can normally do this:

```js
require = {deps: ["foo"]}
script = document.createElement("script");
script.src = '/path/to/require.js';
document.head.appendChild(script);
```

But I'd like to do the name with something that's been namespaced.  However, the code is rewritten only to change the name of `require`, but doesn't change the object that is looked at for configuration.  E.g., I use namespaces to make it define `TOWTRUCK.require` and it still looks for configuration in `require`.

**Comment by jrburke** [comment]
No new info, closing as I believe there is a solution.
